### ISSUE TITLE
choice wlan0 wlan1

### ISSUE THREAD

**Issue by PA3DSS** [idev1/rpihotspot#4]
The script works very well, but should be nice to get the choice for **wlan0** or **wlan1**, as well the DNS because i point the DNS to my Pihole.
Ofcourse i changed it manual but should be nice during install.
Second time i installed the script, i have changed the script

**Comment by idev1** [comment]
Hi, thanks for your feedback !
I have supported a new option "--wifi-interface" to support hardware specific WiFi interface name to be used for network configuration. Please evaluate and close the issue if its satisfying the needful.

Thanks
Pankaj

**Comment by PA3DSS** [comment]
GREAT, thank you ! i inform you again if i have an issue again :)

regards,
Theo

**Comment by idev1** [comment]
Closing the issue since, the actual purpose of taking the virtual WiFi interface names thru script is already met.
