### ISSUE TITLE
On/Off Flag

### ISSUE THREAD

**Issue by up2smoke** [idev1/rpihotspot#5]
Greate Script  :D  :idea:  :mrgreen:  !!! - Use it on rPi Zero W and raspbian Lite
I changed it a bit ... to be able to switch the repeater on and off.
Added to ur Script:

> near Line 39

    startFile="$execDir/start

> near Line 334

    if [ -f "$StartFile" ]; then
        echo "[Remove]: $StartFile"
        rm -f $netStartFile
    fi

> and near Line 585

    # Create startup script without repeater mode
    cat > $StartFile <<EOF
    
    # booting rPi without repeater mode
    
    # Output the standard errors and messages of rc.local executions to rc.local.log file.
    exec 2> $rcLocalLogFile
    exec 1>&2
    
    #Start dhcpcd. Again, a 5-second sleep
    echo "Starting dhcpcd service..."
    systemctl start dhcpcd.service
    sleep 20

    echo "Starting dnsmasq service..."
    systemctl restart dnsmasq.service
    #systemctl start dnsmasq.service

    echo "Enabling netStop service..."
    systemctl enable netStop.service
    systemctl start netStop.service

    echo "Start DONE"
    bash -c 'echo "\$(date +"%Y-%m-%d %T") - REPEATER MODE DEACTIVATED" >>  $netLogFile'
    EOF
    
    chmod ug+x $StartFile

I know, most of them is copy and paste, but i'm not a dev or Something and my english is also bad ^^

> To the end i replaced ur line in /etc/rc.local

     /bash/bin /home/pi/network-setup/bin/netStart

> with

    # Repeater Mode Switch
    _DATEI=repeater || true
    If [ -f "/boot/$_DATEI" ]; then
       /bin/bash /home/pi/network-setup/bin/netStart
    else
       /bin/bash /home/pi/network-setup/bin/start
    fi

Now i can easy switch on/off the repeater mode, with a flag in /boot...
Maybe you like this idea .. I would be glad, if you would integrate it in your script. :mrgreen:

**Comment by idev1** [comment]
Hi, thanks for your feedback!
I am a bit confused with your suggestion to integrate the changes.
Please elaborate so that, I can have a work around on your feedback.

Thanks
Pankaj

**Comment by idev1** [comment]
Closing issue since, there is no further active followup from user.
