### ISSUE TITLE
Abort the script on first error

### ISSUE THREAD

**Issue by frnhr** [idev1/rpihotspot#8]
Sometimes it happens that I lose the network connection (e.g. the cable falls out because the plastic tab is broken... or whatever). In such cases setup-network.sh cannot install software like hostapd, but it still finishes as successful (return code 0). It should abort. 

Perhaps start with `set -e` under the hashbang. If a line is allowed to fail, adding a `!` in front of it will make it not stop the whole script (regardless of return code).

**Comment by idev1** [comment]
Hi Fran

Thanks for pointing out the probable problem which can occur due to interruption (caused by power cable pull out or disconnection from Internet) in the installation.

I will look into this issue if I find a corrective steps and will provide an update.

Thanks
Pankaj

**Comment by frnhr** [comment]
I just test the script after adding the `set -e`. It seems to work ok on both Buster Lite and Stretch Lite, so I made a little PR with the change. Very _little_, probably the smallest PR I have ever made :)

**Comment by idev1** [comment]
Thanks Fran for resolving the issue !! and I have merged the changes also..

Although, I have not fully tested the change but, i believe that the change will support the script installation abort in case if there is any type of error (whether its internet disconnection or any type of soft interruption). 

The only thing where I am guessing that, "set -e" may not work if there is a pipe code execution in the code command and i think, in this respect, "set -o errexit" and "set -o pipefail" options may work but, I need to fully review these updates before I change something in the code. Or, another solution would be to check the success and failure of any code command and then raise an error which will give specific information to the end user about the failure (for e.g., if [ "$(apt install hostapd -y)" ]; then echo "Installation failure of Hostapd. Please check internet connection. Aborting script installation .." ).

Please let me know your suggestion also.

Thanks
Pankaj
