### ISSUE TITLE
Just a note to idev1

### ISSUE THREAD

**Issue by RickMason1** [idev1/rpihotspot#9]
This isn't an issue, just a note.

I have been fighting the AP setup from web sources for a week, then yesterday I found yours.  You have saved this poor little PI from an untimely and sudden demise, and you have reduced my aggravation levels to zero.  Now my aircraft system can communicate with what ever VPN io system that I choose to display flight information about my aircraft systems.  (engine, power, temps. etc.)  This allows me a lot of mounting options.

Thank you
Rick Mason
NX5UX

**Comment by idev1** [comment]
Hi Rick

Thanks for your appreciation ! and I am very happy that the script is serving the purpose you are looking for. If possible, please star this app :) as it will help me to boost up my energy to provide free contribution to the enhancements of this script.

Thank you again for your usage of this script :)

Thanks
Pankaj
